// Bilingual dictionary (English + Telugu) for the public site + portals.
// Telugu translations for navigation, sections, and key labels.

export type Lang = "en" | "te";

export const LANGS: { code: Lang; label: string; native: string }[] = [
  { code: "en", label: "English", native: "English" },
  { code: "te", label: "Telugu", native: "తెలుగు" },
];

type Dict = Record<string, { en: string; te: string }>;

export const t: Dict = {
  // Brand / nav
  "nav.home": { en: "Home", te: "హోమ్" },
  "nav.about": { en: "About", te: "మా గురించి" },
  "nav.academics": { en: "Academics", te: "విద్యావిధానం" },
  "nav.staff": { en: "Staff", te: "ఉపాధ్యాయులు" },
  "nav.facilities": { en: "Facilities", te: "సౌకర్యాలు" },
  "nav.notices": { en: "Notices", te: "సూచనలు" },
  "nav.events": { en: "Events", te: "కార్యక్రమాలు" },
  "nav.achievements": { en: "Achievements", te: "విజయాలు" },
  "nav.ssc": { en: "SSC Corner", te: "ఎస్‌ఎస్‌సి కార్నర్" },
  "nav.contact": { en: "Contact", te: "సంప్రదించండి" },
  "nav.portal": { en: "Portal Login", te: "పోర్టల్ లాగిన్" },

  // Hero
  "hero.badge": { en: "Government School • Est. 1965", te: "ప్రభుత్వ పాఠశాల • స్థాపితం 1965" },
  "hero.title": { en: "ZPHS Kunaparajuparva", te: "జెడ్‌పీహెచ్‌ఎస్ కుణపరాజుపర్వ" },
  "hero.subtitle": {
    en: "A Government High School nurturing Classes VI–X in Telugu medium, serving the children of Kunaparajuparva village, Bapatla Mandal.",
    te: "కుణపరాజుపర్వ గ్రామంలో 6 నుండి 10 తరగతుల విద్యార్థులకు తెలుగు మాధ్యమంలో విద్యాబోధన చేసే ప్రభుత్వ ఉన్నత పాఠశాల.",
  },
  "hero.cta.portal": { en: "Portal Login", te: "పోర్టల్ లాగిన్" },
  "hero.cta.ssc": { en: "SSC Paper Library", te: "ఎస్‌ఎస్‌సి ప్రశ్నపత్రాల లైబ్రరీ" },

  // Sections
  "sec.about.title": { en: "About Our School", te: "మా పాఠశాల గురించి" },
  "sec.academics.title": { en: "Academics — Classes VI to X", te: "విద్యావిధానం — 6 నుండి 10 తరగతులు" },
  "sec.staff.title": { en: "Staff & Leadership", te: "ఉపాధ్యాయులు & నాయకత్వం" },
  "sec.facilities.title": { en: "Facilities", te: "సౌకర్యాలు" },
  "sec.notices.title": { en: "Latest Notices", te: "తాజా సూచనలు" },
  "sec.events.title": { en: "Upcoming Events", te: "రాబోయే కార్యక్రమాలు" },
  "sec.achievements.title": { en: "Achievements", te: "మా విజయాలు" },
  "sec.ssc.title": { en: "SSC Question Paper Library", te: "ఎస్‌ఎస్‌సి ప్రశ్నపత్రాల లైబ్రరీ" },
  "sec.transparency.title": { en: "Transparency & Accessibility", te: "పారదర్శకత & అందుబాటు" },
  "sec.contact.title": { en: "Contact Us", te: "మమ్మల్ని సంప్రదించండి" },

  // Common
  "common.viewAll": { en: "View all", te: "అన్నీ చూడండి" },
  "common.readMore": { en: "Read more", te: "ఇంకా చదవండి" },
  "common.download": { en: "Download", te: "డౌన్‌లోడ్" },
  "common.year": { en: "Year", te: "సంవత్సరం" },
  "common.subject": { en: "Subject", te: "విషయం" },
  "common.medium": { en: "Medium", te: "మాధ్యమం" },
  "common.type": { en: "Type", te: "రకం" },
  "common.search": { en: "Search", te: "శోధించండి" },
  "common.filter": { en: "Filter", te: "వడకట్టు" },
  "common.loading": { en: "Loading…", te: "లోడ్ అవుతోంది…" },
  "common.noResults": { en: "No results found.", te: "ఫలితాలు లేవు." },

  // Footer
  "footer.rights": { en: "All rights reserved.", te: "అన్ని హక్కులూ రిజర్వ్‌డ్." },
  "footer.disclaimer": {
    en: "Hall tickets generated by this platform are internal school examination tickets only and are NOT official AP SSC/DGE hall tickets.",
    te: "ఈ వేదిక జారీ చేసే హాల్ టికెట్లు అంతర్గత పాఠశాల పరీక్షా టికెట్లు మాత్రమే, అధికారిక AP SSC/DGE హాల్ టికెట్లు కావు.",
  },

  // Login
  "login.title": { en: "Portal Login", te: "పోర్టల్ లాగిన్" },
  "login.subtitle": { en: "Sign in to access your role-specific portal.", te: "మీ పాత్ర-ఆధారిత పోర్టల్‌ను యాక్సెస్ చేయడానికి సైన్ ఇన్ చేయండి." },
  "login.email": { en: "Email", te: "ఇమెయిల్" },
  "login.password": { en: "Password", te: "పాస్‌వర్డ్" },
  "login.submit": { en: "Sign in", te: "సైన్ ఇన్" },
  "login.demoTitle": { en: "Demo accounts (password: demo123)", te: "డెమో ఖాతాలు (పాస్‌వర్డ్: demo123)" },
  "login.invalid": { en: "Invalid email or password.", te: "ఇమెయిల్ లేదా పాస్‌వర్డ్ తప్పు." },
  "login.backHome": { en: "Back to website", te: "వెబ్‌సైట్‌కు తిరిగి" },

  // Portal shell
  "portal.dashboard": { en: "Dashboard", te: "డాష్‌బోర్డ్" },
  "portal.students": { en: "Students", te: "విద్యార్థులు" },
  "portal.staff": { en: "Staff", te: "ఉపాధ్యాయులు" },
  "portal.roles": { en: "Roles & Onboarding", te: "పాత్రలు & ఆన్‌బోర్డింగ్" },
  "portal.handover": { en: "HM Handover", te: "HM హ్యాండోవర్" },
  "portal.attendance": { en: "Attendance", te: "హాజరు" },
  "portal.academics": { en: "Academics", te: "విద్యావిధానం" },
  "portal.exams": { en: "Exams", te: "పరీక్షలు" },
  "portal.hallTickets": { en: "Hall Tickets", te: "హాల్ టికెట్లు" },
  "portal.idCards": { en: "ID Cards", te: "ఐడి కార్డులు" },
  "portal.schemes": { en: "Schemes", te: "పథకాలు" },
  "portal.homework": { en: "Homework / LMS", te: "హోంవర్క్ / LMS" },
  "portal.timetable": { en: "Timetable", te: "షెడ్యూల్" },
  "portal.notices": { en: "Notices / CMS", te: "సూచనలు / CMS" },
  "portal.reports": { en: "Reports", te: "నివేదికలు" },
  "portal.audit": { en: "Audit Log", te: "ఆడిట్ లాగ్" },
  "portal.announcements": { en: "Announcements", te: "ప్రకటనలు" },
  "portal.results": { en: "Results & Feedback", te: "ఫలితాలు & అభిప్రాయం" },
  "portal.profile": { en: "Profile", te: "ప్రొఫైల్" },
  "portal.signOut": { en: "Sign out", te: "సైన్ అవుట్" },
  "portal.myClasses": { en: "My Classes", te: "నా తరగతులు" },
  "portal.schemeCases": { en: "Scheme Cases", te: "పథక కేసులు" },
  "portal.printQueue": { en: "Print Queue", te: "ప్రింట్ క్యూ" },
  "portal.today": { en: "Today", te: "ఈరోజు" },
  "portal.child": { en: "Child Dashboard", te: "బాల డాష్‌బోర్డ్" },
};

export function tr(key: string, lang: Lang): string {
  const entry = t[key];
  if (!entry) return key;
  return entry[lang] ?? entry.en;
}
